### ISSUE TITLE
Synthetics MonitorService's list method lists only 20 monitors

### ISSUE THREAD

**Issue by cdchudasama** [opsmatters/newrelic-api#1]
There is an issue with the list method as it only lists 20 monitors. I was unable to find any way to get the next set of 20 monitors or all the monitors at once.

**Comment by opsdemon** [comment]
Thanks for letting me know. It sounds like a default page size, but I'll take a look and let you know.

**Comment by opsdemon** [comment]
As expected, this was due to the list() operation using the default offset and limit (0 and 20).
I've checked in a fix that adds new "offset" and "limit" parameters to the list methods in MonitorService.
Please let me know if this fixes your problem and i'll close the issue.

Please can you and your friends remember to star my repositories if you like the projects and wish to show your support.

Thanks.

**Comment by opsdemon** [comment]
The fix has now been released as 1.0.11
